version: "3"
services:
  rabbitmq:
    container_name: rabbitmq_service
    image: rabbitmq:3.7.14-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=bts
      - RABBITMQ_DEFAULT_PASS=btsbts12
    ports:
      - "5672:5672"
      - "15672:15672"
  config:
    build: .
    container_name: config-server
    restart: always
    ports:
      - "8888:8888"
    depends_on:
      - rabbitmq